"""Added wearing mask

Revision ID: c579c6ad9e26
Revises: 7e3666791d07
Create Date: 2020-07-15 10:25:33.008524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c579c6ad9e26'
down_revision = '7e3666791d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wearing_mask', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wearing_mask')
    # ### end Alembic commands ###
